# Generated by Django 4.1.3 on 2022-12-07 09:56

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoopForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_contact_name', models.CharField(max_length=100, verbose_name="1st Contact's Name")),
                ('first_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="1st Contact's Phone Number")),
                ('first_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="1st Contact's Email")),
                ('second_contact_name', models.CharField(max_length=100, verbose_name="2nd Contact's Name")),
                ('second_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="2nd Contact's Phone Number")),
                ('second_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="2nd Contact's Email")),
                ('third_contact_name', models.CharField(max_length=100, verbose_name="3rd Contact's Name")),
                ('third_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="3rd Contact's Phone Number")),
                ('third_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="3rd Contact's Email")),
                ('society_name', models.CharField(max_length=100, verbose_name='Name of the Society')),
                ('society_category', models.CharField(choices=[('Arts and Science Society', 'Arts and Science Society'), ('Business', 'Business'), ('Caste', 'Caste'), ('Charitable Society', 'Charitable Society'), ('Company Trusts', 'Company Trusts'), ('Crafts', 'Crafts'), ('Educational', 'Educational'), ('Military', 'Military'), ('Political', 'Political'), ('Religious', 'Religious'), ('Sports', 'Sports'), ('Social', 'Social'), ('Women and Children', 'Women and Children'), ('Welfare Association', 'Welfare Association'), ('Youth', 'Youth')], default='Arts and Science Society', max_length=100, verbose_name='Category of the Society')),
                ('society_house_number', models.IntegerField(verbose_name='Door/House/Building Number')),
                ('society_street', models.CharField(max_length=100, verbose_name='Street')),
                ('society_village_city', models.CharField(max_length=70, verbose_name='Village/City')),
                ('society_lga_of_activities', models.CharField(choices=[('Akoko-Edo', 'Akoko-Edo'), ('Egor', 'Egor'), ('Esan Central', 'Esan Central'), ('Esan North-East', 'Esan North-East'), ('Esan South-East', 'Esan South-East'), ('Esan West', 'Esan West'), ('Etsako Central', 'Etsako Central'), ('Etsako East', 'Etsako East'), ('Etsako West', 'Etsako West'), ('Igueben', 'Igueben'), ('Ikpoba-Okha', 'Ikpoba-Okha'), ('Oredo', 'Oredo'), ('Orhiomwon', 'Orhiomwon'), ('Ovia North-East', 'Ovia North-East'), ('Ovia South-East', 'Ovia South-East'), ('Owan East', 'Owan East'), ('Owan West', 'Owan West')], default='Akoko-Edo', max_length=30, verbose_name='LGA of Activities')),
                ('first_purpose', models.CharField(max_length=300, null=True, verbose_name='First Purpose')),
                ('second_purpose', models.CharField(max_length=300, null=True, verbose_name='Second Purpose')),
                ('third_purpose', models.CharField(max_length=300, null=True, verbose_name='Third Purpose')),
                ('nature_registration', models.CharField(max_length=100, null=True, verbose_name='Nature of Registration')),
                ('attach_share_capital', models.FileField(blank=True, null=True, upload_to='documents')),
                ('first_origin_meeting_date', models.DateField(default=datetime.date.today, verbose_name='1st Meeting Date')),
                ('second_origin_meeting_date', models.DateField(default=datetime.date.today, verbose_name='2nd Meeting Date')),
                ('attach_first_minute', models.FileField(upload_to='documents', verbose_name='Attach Minute of First Meeting')),
                ('attach_second_minute', models.FileField(upload_to='documents', verbose_name='Attach Minute of Second Meeting')),
                ('president_name', models.CharField(max_length=100, verbose_name="President's Name")),
                ('president_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="President's Phone Number")),
                ('secretary_name', models.CharField(max_length=100, verbose_name="Secretary's Name")),
                ('secretary_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="Secretary's Phone Number")),
                ('treasurer_name', models.CharField(max_length=100, verbose_name="Treasurer's Name")),
                ('treasurer_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="Treasurer's Phone Number")),
                ('fourth_member_name', models.CharField(max_length=100, verbose_name="4th Member's Name")),
                ('fourth_member_position', models.CharField(max_length=100, verbose_name="4th Member's Position")),
                ('fourth_member_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="4th Member's Phone Number")),
                ('fifth_member_name', models.CharField(max_length=100, verbose_name="5th Member's Name")),
                ('fifth_member_position', models.CharField(max_length=100, verbose_name="5th Member's Position")),
                ('fifth_member_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="5th Member's Phone Number")),
                ('sixth_member_name', models.CharField(max_length=100, verbose_name="6th Member's Name")),
                ('sixth_member_position', models.CharField(max_length=100, verbose_name="6th Member's Position")),
                ('sixth_member_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="6th Member's Phone Number")),
                ('seventh_member_name', models.CharField(max_length=100, verbose_name="7th Member's Name")),
                ('seventh_member_position', models.CharField(max_length=100, verbose_name="7th Member's Position")),
                ('seventh_member_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="7th Member's Phone Number")),
                ('eighth_member_name', models.CharField(max_length=100, verbose_name="8th Member's Name")),
                ('eighth_member_position', models.CharField(max_length=100, verbose_name="8th Member's Position")),
                ('eighth_member_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="8th Member's Phone Number")),
                ('ninth_member_name', models.CharField(max_length=100, verbose_name="9th Member's Name")),
                ('ninth_member_position', models.CharField(max_length=100, verbose_name="9th Member's Position")),
                ('ninth_member_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="9th Member's Phone Number")),
                ('tenth_member_name', models.CharField(max_length=100, verbose_name="10th Member's Name")),
                ('tenth_member_position', models.CharField(max_length=100, verbose_name="10th Member's Position")),
                ('tenth_member_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="10th Member's Phone Number")),
                ('first_trustee_name', models.CharField(max_length=100, verbose_name="1st Trustee's Name")),
                ('first_trustee_position', models.CharField(max_length=100, verbose_name="1st Trustee's Position")),
                ('first_trustee_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="1st Trustee's Phone Number")),
                ('second_trustee_name', models.CharField(max_length=100, verbose_name="2nd Trustee's Name")),
                ('second_trustee_position', models.CharField(max_length=100, verbose_name="2nd Trustee's Position")),
                ('second_trustee_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="2nd Trustee's Phone Number")),
                ('third_trustee_name', models.CharField(max_length=100, verbose_name="3rd Trustee's Name")),
                ('third_trustee_position', models.CharField(max_length=100, verbose_name="3rd Trustee's Position")),
                ('third_trustee_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="3rd Trustee's Phone Number")),
                ('fourth_trustee_name', models.CharField(max_length=100, verbose_name="4th Trustee's Name")),
                ('fourth_trustee_position', models.CharField(max_length=100, verbose_name="4th Trustee's Position")),
                ('fourth_trustee_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="4th Trustee's Phone Number")),
                ('have_bye_laws', models.CharField(max_length=128, null=True, verbose_name='Bye-Laws?')),
                ('attach_bye_laws', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Attach a copy of your Bye-Laws')),
            ],
            options={
                'db_table': 'form_coopform',
            },
        ),
    ]
