# Generated by Django 4.1.3 on 2023-01-04 18:24

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_coopform_attach_share_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopform',
            name='society_logo',
            field=models.ImageField(blank=True, default='default.png', upload_to=form.models.CoopForm.get_upload_path, verbose_name="Society's Logo"),
        ),
        migrations.AlterField(
            model_name='sharecapitalfiles',
            name='attach_share_capital',
            field=models.FileField(blank=True, upload_to=form.models.shareCapitalFiles.get_upload_path, verbose_name='Attach Share Capital'),
        ),
    ]
