# Generated by Django 4.2 on 2023-04-21 15:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import form.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0005_alter_coopform_society_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopform',
            name='is_cooperative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coopform',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='attach_bye_laws',
            field=models.FileField(blank=True, upload_to=form.models.CoopForm.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg'])], verbose_name='Attach a copy of your Bye-Laws'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='attach_first_minute',
            field=models.FileField(upload_to=form.models.CoopForm.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg'])], verbose_name='Attach Minute of First Meeting'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='attach_second_minute',
            field=models.FileField(upload_to=form.models.CoopForm.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg'])], verbose_name='Attach Minute of Second Meeting'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='first_contact_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name="1st Contact's Email"),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='first_contact_name',
            field=models.CharField(max_length=50, verbose_name="1st Contact's Name"),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_category',
            field=models.CharField(choices=[('Arts and Science Society', 'Arts and Science Society'), ('Business', 'Business'), ('Caste', 'Caste'), ('Charitable Society', 'Charitable Society'), ('Company Trusts', 'Company Trusts'), ('Crafts', 'Crafts'), ('Educational', 'Educational'), ('Military', 'Military'), ('Political', 'Political'), ('Religious', 'Religious'), ('Sports', 'Sports'), ('Social', 'Social'), ('Women and Children', 'Women and Children'), ('Welfare Association', 'Welfare Association'), ('Youth', 'Youth')], default='Arts and Science Society', max_length=50, verbose_name='Category of the Society'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_logo',
            field=models.ImageField(blank=True, default="C:\\Users\\Admin\\Downloads\\EA\\djangoprojects\\coopformapp\\form/templates/static/'img/default.png'", upload_to=form.models.CoopForm.get_upload_path, verbose_name="Society's Logo"),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name of the Society'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_street',
            field=models.CharField(max_length=70, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_village_city',
            field=models.CharField(max_length=30, verbose_name='Village/City'),
        ),
        migrations.AlterField(
            model_name='sharecapitalfiles',
            name='attach_share_capital',
            field=models.FileField(blank=True, upload_to=form.models.shareCapitalFiles.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg'])], verbose_name='Attach Share Capital'),
        ),
    ]
