# Generated by Django 4.2 on 2023-04-23 18:57

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_coopform_is_cooperative_coopform_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coopform',
            options={'permissions': (('can_go_dehradoon', 'Trip to Dehradoon'),)},
        ),
        migrations.AlterField(
            model_name='coopform',
            name='is_cooperative',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_logo',
            field=models.ImageField(blank=True, default="C:\\Users\\Admin\\Downloads\\EA\\djangoprojects\\coopformapp\\form/templates/static/'img/default.png'", upload_to=form.models.CoopForm.get_upload_path, verbose_name="Society's Logo"),
        ),
    ]
