# Generated by Django 4.2 on 2023-04-23 18:59

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_coopform_options_alter_coopform_is_cooperative_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coopform',
            options={'permissions': (('can_go_dehradoon', 'Can view Finish'),)},
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_logo',
            field=models.ImageField(blank=True, default="C:\\Users\\Admin\\Downloads\\EA\\djangoprojects\\coopformapp\\form/templates/static/'img/default.png'", upload_to=form.models.CoopForm.get_upload_path, verbose_name="Society's Logo"),
        ),
    ]
