# Generated by Django 4.2 on 2023-05-07 00:48

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_alter_coopform_options_alter_coopform_society_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coopform',
            name='is_cooperative',
        ),
        migrations.RemoveField(
            model_name='coopform',
            name='user',
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_logo',
            field=models.ImageField(blank=True, default='C:\\Users\\Admin\\Downloads\\EA\\djangoprojects\\coopformapp\\form/templates/static/img/default.png', upload_to=form.models.CoopForm.get_upload_path, verbose_name="Society's Logo"),
        ),
    ]
