# Generated by Django 4.2 on 2023-08-09 22:47

import django.core.validators
from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_coopform_society_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopform',
            name='attach_first_minute',
            field=models.FileField(upload_to=form.models.CoopForm.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'png', 'jpg'])], verbose_name='Attach Minute of First Meeting'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='attach_second_minute',
            field=models.FileField(upload_to=form.models.CoopForm.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'png', 'jpg'])], verbose_name='Attach Minute of Second Meeting'),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coopform',
            name='society_logo',
            field=models.ImageField(blank=True, default='C:\\Users\\Admin\\Downloads\\EA\\djangoprojects\\coopformapp\\form/templates/static/img/default.png', upload_to=form.models.CoopForm.get_upload_path, verbose_name="Society's Logo"),
        ),
        migrations.AlterField(
            model_name='sharecapitalfiles',
            name='attach_share_capital',
            field=models.FileField(blank=True, upload_to=form.models.shareCapitalFiles.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'png', 'jpg'])], verbose_name='Attach Share Capital'),
        ),
    ]
